// Package repo holds catalog's data access. SQL is hand-written rather than
// generated by an ORM, because the query plans are part of the point: Phase 7
// tunes these statements with EXPLAIN ANALYZE, which is far harder when a
// framework is composing the SQL.
package repo

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/abhiraj860/ticketflow/services/catalog-svc/internal/domain"
)

// EventRepo reads catalog data from Postgres.
type EventRepo struct {
	pool *pgxpool.Pool
}

func NewEventRepo(pool *pgxpool.Pool) *EventRepo {
	return &EventRepo{pool: pool}
}

// eventColumns is shared by GetEvent and ListEvents so the two cannot drift
// apart in column order, which is a classic source of silent scan bugs.
const eventColumns = `
	e.id, e.title, e.kind, e.status, e.seat_map_id,
	e.starts_at, e.ends_at, e.sale_opens_at, e.poster_url, e.tags,
	e.version, e.updated_at,
	v.id, v.name, v.city, v.country_code, v.address,
	COALESCE(v.latitude, 0), COALESCE(v.longitude, 0)`

// scanEvent reads one row in eventColumns order.
func scanEvent(row pgx.Row) (domain.Event, error) {
	var e domain.Event
	err := row.Scan(
		&e.ID, &e.Title, &e.Kind, &e.Status, &e.SeatMapID,
		&e.StartsAt, &e.EndsAt, &e.SaleOpensAt, &e.PosterURL, &e.Tags,
		&e.Version, &e.UpdatedAt,
		&e.Venue.ID, &e.Venue.Name, &e.Venue.City, &e.Venue.CountryCode,
		&e.Venue.Address, &e.Venue.Latitude, &e.Venue.Longitude,
	)
	return e, err
}

// GetEvent returns one event with its venue and pricing tiers.
//
// Two queries rather than one join: joining pricing_tier would multiply the
// event row by the number of tiers, and the de-duplication that follows costs
// more than a second indexed lookup on a primary key.
func (r *EventRepo) GetEvent(ctx context.Context, id string) (domain.Event, error) {
	const q = `SELECT ` + eventColumns + `
		FROM event e
		JOIN venue v ON v.id = e.venue_id
		WHERE e.id = $1`

	event, err := scanEvent(r.pool.QueryRow(ctx, q, id))
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.Event{}, domain.ErrNotFound
	}
	if err != nil {
		return domain.Event{}, fmt.Errorf("catalog: querying event %q: %w", id, err)
	}

	tiers, err := r.pricingTiers(ctx, id)
	if err != nil {
		return domain.Event{}, err
	}
	event.PricingTiers = tiers

	return event, nil
}

func (r *EventRepo) pricingTiers(ctx context.Context, eventID string) ([]domain.PricingTier, error) {
	const q = `
		SELECT id, name, amount_minor, currency_code
		FROM pricing_tier
		WHERE event_id = $1
		ORDER BY amount_minor`

	rows, err := r.pool.Query(ctx, q, eventID)
	if err != nil {
		return nil, fmt.Errorf("catalog: querying pricing tiers for %q: %w", eventID, err)
	}
	defer rows.Close()

	var tiers []domain.PricingTier
	for rows.Next() {
		var t domain.PricingTier
		if err := rows.Scan(&t.ID, &t.Name, &t.Price.AmountMinor, &t.Price.CurrencyCode); err != nil {
			return nil, fmt.Errorf("catalog: scanning pricing tier: %w", err)
		}
		tiers = append(tiers, t)
	}
	// rows.Err() is easy to forget and silently truncates results on a mid-scan
	// failure; the rowserrcheck linter enforces it.
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("catalog: iterating pricing tiers: %w", err)
	}
	return tiers, nil
}

// ListEvents returns a page of browsable events ordered by start time.
//
// Only ANNOUNCED and ON_SALE events are returned, which lets the query use the
// partial index event_browse_idx (status, starts_at). Because the index is
// already ordered by starts_at, it satisfies the ORDER BY too -- the plan has
// no sort node.
func (r *EventRepo) ListEvents(ctx context.Context, f domain.ListFilter) (domain.Page[domain.Event], error) {
	cursor, err := decodeCursor(f.PageToken)
	if err != nil {
		return domain.Page[domain.Event]{}, err
	}

	// Fetch one extra row to determine whether a further page exists, without
	// paying for a separate COUNT query.
	limit := f.PageSize + 1

	var (
		conds = []string{"e.status IN (1, 2)"}
		args  []any
	)
	add := func(cond string, val any) {
		args = append(args, val)
		conds = append(conds, fmt.Sprintf(cond, len(args)))
	}

	if f.City != "" {
		add("v.city = $%d", f.City)
	}
	if f.Kind != domain.EventKindUnspecified {
		add("e.kind = $%d", int16(f.Kind))
	}
	if !cursor.startsAt.IsZero() {
		// Keyset pagination on (starts_at, id). OFFSET would make page N cost
		// O(N * page_size) as a user pages deeper; this stays O(page_size)
		// because the composite index seeks straight to the cursor position.
		args = append(args, cursor.startsAt, cursor.id)
		conds = append(conds, fmt.Sprintf("(e.starts_at, e.id) > ($%d, $%d)", len(args)-1, len(args)))
	}
	args = append(args, limit)

	q := `SELECT ` + eventColumns + `
		FROM event e
		JOIN venue v ON v.id = e.venue_id
		WHERE ` + strings.Join(conds, " AND ") + `
		ORDER BY e.starts_at, e.id
		LIMIT $` + fmt.Sprint(len(args))

	rows, err := r.pool.Query(ctx, q, args...)
	if err != nil {
		return domain.Page[domain.Event]{}, fmt.Errorf("catalog: listing events: %w", err)
	}
	defer rows.Close()

	var events []domain.Event
	for rows.Next() {
		e, err := scanEvent(rows)
		if err != nil {
			return domain.Page[domain.Event]{}, fmt.Errorf("catalog: scanning event: %w", err)
		}
		events = append(events, e)
	}
	if err := rows.Err(); err != nil {
		return domain.Page[domain.Event]{}, fmt.Errorf("catalog: iterating events: %w", err)
	}

	page := domain.Page[domain.Event]{Items: events}
	if int32(len(events)) == limit {
		// The extra row proves there is more; drop it and emit a cursor.
		last := events[len(events)-2]
		page.Items = events[:len(events)-1]
		page.NextPageToken = encodeCursor(cursor2{startsAt: last.StartsAt, id: last.ID})
	}

	// Listing deliberately omits pricing tiers: a browse page renders a "from
	// Rs X" badge that search-svc supplies, and issuing one tier query per
	// event here would be a textbook N+1.
	return page, nil
}

// GetSeatMap returns a seat map and all of its seats.
//
// This is the single most cacheable object in the system: an arena seat map is
// tens of thousands of rows that change essentially never. It is fetched once
// and served from cache for hours.
func (r *EventRepo) GetSeatMap(ctx context.Context, id string) (domain.SeatMap, error) {
	const mapQ = `
		SELECT id, venue_id, viewbox_width, viewbox_height, version
		FROM seat_map WHERE id = $1`

	var m domain.SeatMap
	err := r.pool.QueryRow(ctx, mapQ, id).Scan(
		&m.ID, &m.VenueID, &m.ViewboxWidth, &m.ViewboxHeight, &m.Version)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.SeatMap{}, domain.ErrNotFound
	}
	if err != nil {
		return domain.SeatMap{}, fmt.Errorf("catalog: querying seat map %q: %w", id, err)
	}

	const seatQ = `
		SELECT id, section, row_label, seat_number, pricing_tier_id, x, y
		FROM seat
		WHERE seat_map_id = $1
		ORDER BY section, row_label, seat_number`

	rows, err := r.pool.Query(ctx, seatQ, id)
	if err != nil {
		return domain.SeatMap{}, fmt.Errorf("catalog: querying seats for %q: %w", id, err)
	}
	defer rows.Close()

	for rows.Next() {
		var s domain.Seat
		if err := rows.Scan(&s.ID, &s.Section, &s.Row, &s.Number,
			&s.PricingTierID, &s.X, &s.Y); err != nil {
			return domain.SeatMap{}, fmt.Errorf("catalog: scanning seat: %w", err)
		}
		m.Seats = append(m.Seats, s)
	}
	if err := rows.Err(); err != nil {
		return domain.SeatMap{}, fmt.Errorf("catalog: iterating seats: %w", err)
	}

	return m, nil
}

// cursor2 is the keyset position: the last row's sort key.
type cursor2 struct {
	startsAt time.Time
	id       string
}

// encodeCursor produces an opaque page token. Opaque on purpose -- clients that
// parse a cursor end up depending on the sort order, which then cannot change.
func encodeCursor(c cursor2) string {
	raw := c.startsAt.UTC().Format(time.RFC3339Nano) + "|" + c.id
	return base64.RawURLEncoding.EncodeToString([]byte(raw))
}

func decodeCursor(token string) (cursor2, error) {
	if token == "" {
		return cursor2{}, nil
	}
	raw, err := base64.RawURLEncoding.DecodeString(token)
	if err != nil {
		return cursor2{}, fmt.Errorf("catalog: malformed page token: %w", err)
	}
	ts, id, ok := strings.Cut(string(raw), "|")
	if !ok {
		return cursor2{}, errors.New("catalog: malformed page token")
	}
	startsAt, err := time.Parse(time.RFC3339Nano, ts)
	if err != nil {
		return cursor2{}, fmt.Errorf("catalog: malformed page token timestamp: %w", err)
	}
	return cursor2{startsAt: startsAt, id: id}, nil
}
