import math
print(math.fmod(-10, 3))
print(math.floor(3 / 2))
print(math.ceil(3/2))
print(math.sqrt(2))
print(math.pow(2, 3))
print(float("inf") > 10)
print(float("-inf") > 10)
print(math.pow(2, 200))
print(math.pow(2, 200) < float("inf"))