apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arbiter-lite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhiraj/arbiter-lite.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: arbiter-lite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
